#!/usr/bin/env bash
set -euo pipefail

acr_name="gustavo2acr"
echo "Logging into Azure Container Registry"
az acr login --name $acr_name
login_server=$(az acr show --name $acr_name --query loginServer --output tsv)

repository="archetype"
tag="latest" # git rev-parse --short HEAD
image_full_name="$login_server/$repository:$tag"
echo "Building docker image as $image_full_name"

echo "Building $image_full_name"
docker build . -t $image_full_name

echo "Pushing $image_full_name to $acr_name"
docker push $image_full_name